### ISSUE TITLE
Customer page

### ISSUE THREAD

**Issue by codemvp** [marvinvperez/accountgo#2]
Customer page needs to be able to add contacts and primary contact. It is ideal to make add contact in a separate view or in a dialog box. Same as adding Vendor contact.

**Comment by bahmani00** [comment]
for the contact, I added more fields like Address1, Address2, emails,  phones. and also the edit feature:
but I used FluentBootstrap which makes to write much less html tags:


using FluentBootstrap;
@using System.Web.Mvc;

@model Web.Models.ViewModels.ContactViewModel
@{
    Layout = null;
    var bootstrap = @Html.Bootstrap();
}

@using (var form = bootstrap.Form("AddEditCustomerContact", "Sales", FormMethod.Post, null).SetHorizontal(3).Begin())
{
    using (bootstrap.Div().AddCss("panel panel-default panel-body").Begin())
    {
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.PartyId)
        @form.InputFor(x => x.FirstName)
        @form.InputFor(x => x.MiddleName)
        @form.InputFor(x => x.LastName)
        
        @form.InputFor(m => m.Address1)
        @form.InputFor(m => m.Address2)
        @form.InputFor(m => m.Emails).AddAttribute("data-role", "tagsinput")
        @form.InputFor(m => m.Phones).AddAttribute("data-role", "tagsinput")

        
        <div class="form-group">
            <label class="col-md-3 control-label">Country</label>
            <div class="col-md-9">
                <select id="country" name="country">
                    <option value="1" selected="selected">Canada</option>
                    <option value="2">United States</option>
                </select>
            </div>
        </div>
 
        <div>
            <input type="submit" value="Save" name="SaveContact" id="SaveContact" class="btn btn-default" />
            <input type="button" value="Cancel" onclick="$('#addCustomerContact').dialog('close');" class="btn btn-default" />
        </div>    
    }
}

and for showing them in AddOrEditCustomer.cshtml I added the following after AddContact button :
@using (Html.Bootstrap().Div().Begin())
{
    using (var table = Html.Bootstrap(this).Table().SetStyle(TableStyle.Striped).Begin())
    {
        @table.TableHeaderRow("Name", "Phones", "Emails", "Address1")
        foreach (var contact in Model.Contacts)
        {
            @table.TableDataRow(Html.ActionLink(contact.FullName, "AddEditCustomerContact", new { id = contact.Id }, new { @name = "btnAddEditContact" }), contact.Phones, contact.Emails, contact.Address1)
        }
    }
}

It's a personal taste but I prefer to use FluentBootstrap rather than writing all bootstrap-ish tags :)

**Comment by codemvp** [comment]
Hi Daniel,

I've merged your changes from your pork for button print and EFCache. You will see your name in the contributors area which is getting higher and thanks for that.

For this issue, can I request you to create a new fork and apply your changes so I can merge this as well. However, instead of using FluentBootstrap, can you make use of the default bootstrap that we already have. As much as possible we'd like to avoid to many dependencies.

Cheers,
Marvin

**Comment by rwobben** [comment]
Is this still a open issue or is it resolved already.
Im a beginner in asp.net mvc 5. 
Maybe I can give it a try to solve it as soon as I exaclty know what schould be on the customer page.

**Comment by marvinvperez** [comment]
Hi,it is now closed. Maybe you coud try some other pages.
