### ISSUE TITLE
Party Error When Adding Customer / Vendor

### ISSUE THREAD

**Issue by CompleteCoders** [marvinvperez/accountgo#28]
Not sure what the party table is meant to do.  I am getting an error when creating a new vendor because party is null in the following code.  I would have tried to fix it but I don't understand how the Party table is used in the system.

            if (model.Id != 0)
            {
                vendor = _purchasingService.GetVendorById(model.Id.Value);
            }
            else
            {
                vendor = new Vendor();
            }
            
            vendor.Party.Name = model.VendorName;

**Comment by codemvp** [comment]
Hi,
Apology for late reply. The Party entity is a common object for Customer,
Vendor and Contact. Initially, It was designed as abstract class and
Customer, Vendor, and Contact derived from it. (i.e. Customer: Party,
Vendor : Party, Contact : Party).

However, the latest EF7 seems like have an issue mapping to it so we've put
this as a Navigation property.

So you need to initialize the Party when you create a new instance of the
Vendor.

Hope that helps!

Cheers,
Marvs

**Comment by CompleteCoders** [comment]
Thanks.  I haven't worked in open source ever before.  Is this something I should fix and request a pull for?  As far as I can see the add customer and add vendor is completely broken at the moment.

**Comment by codemvp** [comment]
No worries. I assume you have forked the project. Feel free to send a pull request.

-----Original Message-----
