### ISSUE TITLE
Can't Update Database with Update-Database

### ISSUE THREAD

**Issue by hamedmaleki1366** [marvinvperez/accountgo#47]
after change connectionStrings in web.config and project.json and create a empty Database in SQL Server and execute AccountGoWeb and Api , now show error to me that "Company" is not valid object.

so , how can i create tables in empty Database with Ef Migration or Update-Database , Where can i do this (which project must be active in Package Manager)?

thank you all.

**Comment by lancevgarcia** [comment]
Hi! Ef code first is not yet setup. You can setup your database by publishing the project Sql.AccountGo and select your connection. Also check the Allow different platform so you can publish it on your local database. Let me know if this works. Thanks.
